---
- name: fetch 24 hours of monitoring text files
  hosts: []
  remote_user: []
  vars:
    output_dir: /path/to/dir
  become: false

  tasks:

   - name: fetch buffer monitor text
     get_url:
       url: ftp://[user[:pass]]@host.domain[:port]/path
       dest: "{{ output_dir }}/BufferMonitor.txt"

    - name: fetch interface stats text
      get_url:
        url: ftp://[user[:pass]]@host.domain[:port]/path
        dest: "{{ output_dir }}/InterfaceStats.txt"

    - name: fetch logs
      get_url:
        url: ftp://[user[:pass]]@host.domain[:port]/path
        dest: "{{ output_dir }}/Logs.txt"
