---
- name: fetch 24 hours of cisco monitor stats and logs, in 1 hour increments
  hosts: []
  become: false
  remote_user: []

  tasks:

    - name: save latest hour of buffer monitor, interface stats, and logs to cisco memory
      cisco.ios.ios_commands:
        commands:
        - event manager applet MONITORING authorization bypass
        - event timer watchdog time 3600  
        - action 1.0 syslog msg "TAC - Collecting QoS statistics and buffering info"
        - action 1.1 cli command "enable"
        - action 1.2 cli command "show platf hardware fed switch 1 qos queue stats internal port_type egress-cpu asic 0 | append flash:BufferMonitor.txt"
        - action 1.3 cli command "show platf hardware fed switch 1 qos queue stats internal port_type egress-cpu asic 1 | append flash:BufferMonitor.txt"
        - action 1.4 cli command "show platf hardware fed switch 1 qos queue stats internal port_type egress-cpu asic 2 | append flash:BufferMonitor.txt"
        - action 1.5 cli command "show platf hardware fed switch 1 qos queue stats internal port_type egress-cpu asic 3 | append flash:BufferMonitor.txt"
        - action 1.6 cli command "show platf hardware fed switch 2 qos queue stats internal port_type egress-cpu asic 0 | append flash:BufferMonitor.txt"
        - action 1.7 cli command "show platf hardware fed switch 2 qos queue stats internal port_type egress-cpu asic 1 | append flash:BufferMonitor.txt"
        - action 1.8 cli command "show platf hardware fed switch 2 qos queue stats internal port_type egress-cpu asic 2 | append flash:BufferMonitor.txt"
        - action 1.9 cli command "show platf hardware fed switch 2 qos queue stats internal port_type egress-cpu asic 3 | append flash:BufferMonitor.txt"
        - action 2.0 cli command "show platform hardware fed switch 1 fwd-asic register read register-name AqmDtsGlobalSoftLimit | append flash:BufferMonitor.txt"
        - action 2.1 cli command "show platform hardware fed switch 2 fwd-asic register read register-name AqmDtsGlobalSoftLimit | append flash:BufferMonitor.txt"
        - action 2.2 cli command "show platform hardware fed switch 1 fwd-asic register read register-name AqmDtsGlobalSoftBufCnt | append flash:BufferMonitor.txt"
        - action 2.3 cli command "show platform hardware fed switch 2 fwd-asic register read register-name AqmDtsGlobalSoftBufCnt | append flash:BufferMonitor.txt"
        - action 2.4 cli command "show platform hardware fed sw 1 qos queue stats interface fo1/1/1 | append flash:BufferMonitor.txt"
        - action 2.5 cli command "show platform hardware fed sw 2 qos queue stats interface fo2/1/1 | append flash:BufferMonitor.txt"
        - action 2.6 cli command "show spanning-tree summary | append flash:BufferMonitor.txt"
        - action 2.7 cli command "show spanning-tree interface Fo1/1/1 detail | append flash:BufferMonitor.txt"
        - action 2.8 cli command "show spanning-tree interface Fo2/1/1 detail | append flash:BufferMonitor.txt"
        - action 2.9 cli command "show spanning-tree inconsis | append flash:BufferMonitor.txt"
        - action 3.0 cli command "show interface fo1/1/1 | append flash:InterfaceStats.txt
        - action 3.1 cli command "show interface fo2/1/1 | append flash:InterfaceStats.txt
        - action 3.2 cli command "show logging | append flash:Logs.txt"
        - action 3.3 syslog msg "TAC - Finished recollection of logs"
