---
- name: fetch 24 hours of cisco monitor stats and logs, in 1 hour increments
  hosts: []
  become: false
  remote_user: []

  tasks:

    - name: save latest hour of buffer monitor, interface stats, and logs to cisco memory
      cisco.ios.ios_commands:
        commands:
        - syslog msg "tac - collecting qos statistics and buffering info"
        - enable
        - show platf hardware fed switch 1 qos queue stats internal port_type egress-cpu asic 0 | append flash:BufferMonitor.txt
        - show platf hardware fed switch 1 qos queue stats internal port_type egress-cpu asic 1 | append flash:BufferMonitor.txt
        - show platf hardware fed switch 1 qos queue stats internal port_type egress-cpu asic 2 | append flash:BufferMonitor.txt
        - show platf hardware fed switch 1 qos queue stats internal port_type egress-cpu asic 3 | append flash:BufferMonitor.txt
        - show platf hardware fed switch 2 qos queue stats internal port_type egress-cpu asic 0 | append flash:BufferMonitor.txt
        - show platf hardware fed switch 2 qos queue stats internal port_type egress-cpu asic 1 | append flash:BufferMonitor.txt
        - show platf hardware fed switch 2 qos queue stats internal port_type egress-cpu asic 2 | append flash:BufferMonitor.txt
        - show platf hardware fed switch 2 qos queue stats internal port_type egress-cpu asic 3 | append flash:BufferMonitor.txt
        - show platform hardware fed switch 1 fwd-asic register read register-name AqmDtsGlobalSoftLimit | append flash:BufferMonitor.txt
        - show platform hardware fed switch 2 fwd-asic register read register-name AqmDtsGlobalSoftLimit | append flash:BufferMonitor.txt
        - show platform hardware fed switch 1 fwd-asic register read register-name AqmDtsGlobalSoftBufCnt | append flash:BufferMonitor.txt
        - show platform hardware fed switch 2 fwd-asic register read register-name AqmDtsGlobalSoftBufCnt | append flash:BufferMonitor.txt
        - show platform hardware fed sw 1 qos queue stats interface fo1/1/1 | append flash:BufferMonitor.txt
        - show platform hardware fed sw 2 qos queue stats interface fo2/1/1 | append flash:BufferMonitor.txt
        - show spanning-tree summary | append flash:BufferMonitor.txt
        - show spanning-tree interface Fo1/1/1 detail | append flash:BufferMonitor.txt
        - show spanning-tree interface Fo2/1/1 detail | append flash:BufferMonitor.txt
        - show spanning-tree inconsis | append flash:BufferMonitor.txt
        - show interface fo1/1/1 | append flash:InterfaceStats.txt
        - show interface fo2/1/1 | append flash:InterfaceStats.txt
        - show logging | append flash:Logs.txt
        - syslog msg "tac - finished collection of logs"
