---
- name: Measure and Record Fiber Light-Loss on Select Inter-Switch Links
  hosts: ?
  vars:
    border_firewall_address_1: xxx.xxx.xxx.xxx
    border_firewall_address_2: aaa.aaa.aaa.aaa
    domain_controller_01: bbb.bbb.bbb.bbb
    #To set a specified output location, uncomment below and in task 'Save output to ansible host'
    output_localtion : /path/to/record_light-loss.txt
  tasks:
  
  - name: Change to privileged mode
    cisco.ios.ios_command:
      commands: enable

  - name: Gather information on interfaces
    cisco.ios.ios_command:
      commands: sh ip interface brief

  - name: Print neighbor data structure
    cisco.ios.ios_command:
      commands: sh ip ospf neighbor

  - name: Print connection to local devices
    cisco.ios.ios_command:
      commands:
      - ping "{{ border_firewall_address_1 }}"
      - ping "{{ border_firewall_address_2 ))"
      - ping "{{ domain_controller_01 }}"

  - name: Enable Cisco digital optical monitoring
    cisco.ios.ios_config:
      lines:
      - transceiver type all
      - monitoring

  - name: Show interface information
    cisco.ios.ios_command:
      commands: show interface transceiver
    register: output
  
  - name: Create files directory on ansible host if it does not exist
    file:
      state: directory
      path: "{{ playbook_dir }}/files }}"
    delegate_to: localhost
    
  - name: Save output to ansible host
    copy:
      content: "{{ output | to_nice_json }}"
#      dest: "{{ output_localtion }}"
      dest: "{{ playbook_dir }}/files/record_light-loss.txt"
    delegate_to: localhost
     

  - name: disable cisco digital optical monitoring
    cisco.ios.ios_config:
      lines:
      - transceiver type all
      - monitoring
      - no monitoring
  
